// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVcNBUQrjXigVRmATUNuyaUi_0UodtQ_I',
    appId: '1:825621911633:web:356a8e9cc7ac2feeee4070',
    messagingSenderId: '825621911633',
    projectId: 'z-ambulances',
    authDomain: 'z-ambulances.firebaseapp.com',
    databaseURL: 'https://z-ambulances-default-rtdb.firebaseio.com',
    storageBucket: 'z-ambulances.appspot.com',
    measurementId: 'G-3KDGVKCLMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmEtd6MnmUAAf8KKYLgKpuItQFqDbkhY4',
    appId: '1:825621911633:android:abbafc4bcb036cedee4070',
    messagingSenderId: '825621911633',
    projectId: 'z-ambulances',
    databaseURL: 'https://z-ambulances-default-rtdb.firebaseio.com',
    storageBucket: 'z-ambulances.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDNeNT7ujivZparKrz5woG-2CbgQUJPVA',
    appId: '1:825621911633:ios:ab9d452611266745ee4070',
    messagingSenderId: '825621911633',
    projectId: 'z-ambulances',
    databaseURL: 'https://z-ambulances-default-rtdb.firebaseio.com',
    storageBucket: 'z-ambulances.appspot.com',
    iosClientId: '825621911633-d5pdi07bbr7tmi4fn8vls8isgqjj2kg6.apps.googleusercontent.com',
    iosBundleId: 'bundle.id',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDNeNT7ujivZparKrz5woG-2CbgQUJPVA',
    appId: '1:825621911633:ios:b95e28943da20f62ee4070',
    messagingSenderId: '825621911633',
    projectId: 'z-ambulances',
    databaseURL: 'https://z-ambulances-default-rtdb.firebaseio.com',
    storageBucket: 'z-ambulances.appspot.com',
    iosClientId: '825621911633-pmv6sv0hpi5371chjjcjuqqu4tv7ddsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.tagxiuser.RunnerTests',
  );
}
